services:
  - type: web
    name: django-web-service
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn digitalmenu.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: digitalmenu.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: Custom_digitalmenu.onrender.com
