# Generated by Django 5.2.1 on 2025-06-09 06:15

import cloudinary.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='background_image')),
                ('layout', models.CharField(choices=[('column', 'Column'), ('row', 'Row')], default='column', max_length=10)),
                ('logo_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('menu_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lobster', 'Lobster'), ('Pacifico', 'Pacifico'), ('Vendya', 'Vendya'), ('Caviar Dreams', 'Caviar Dreams'), ('Gavoline', 'Gavoline'), ('Heavitas', 'Heavitas'), ('LemonMilk', 'LemonMilk'), ('MoonTank', 'MoonTank'), ('Vogue', 'Vogue')], default='Roboto', max_length=100)),
                ('font_size', models.CharField(choices=[('14px', 'Small'), ('16px', 'Normal'), ('20px', 'Large'), ('24px', 'Extra Large')], default='16px', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_image')),
                ('image_position', models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menuconfig')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='menu_item_image')),
                ('image_position', models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10)),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lobster', 'Lobster'), ('Pacifico', 'Pacifico'), ('Vendya', 'Vendya'), ('Caviar Dreams', 'Caviar Dreams'), ('Gavoline', 'Gavoline'), ('Heavitas', 'Heavitas'), ('LemonMilk', 'LemonMilk'), ('MoonTank', 'MoonTank'), ('Vogue', 'Vogue')], default='Roboto', max_length=100)),
                ('font_size', models.CharField(choices=[('14px', 'Small'), ('16px', 'Normal'), ('20px', 'Large'), ('24px', 'Extra Large')], default='16px', max_length=10)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
        ),
    ]
