# Generated by Django 5.2.1 on 2025-06-02 10:28

import cloudinary.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='menu_config',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='menuconfig',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='menuconfig',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='menuconfig',
            name='letter_spacing',
        ),
        migrations.RemoveField(
            model_name='menuconfig',
            name='line_height',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='position',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='category',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lobster', 'Lobster'), ('Pacifico', 'Pacifico'), ('Vendya', 'Vendya'), ('Caviar Dreams', 'Caviar Dreams'), ('Gavoline', 'Gavoline'), ('Heavitas', 'Heavitas'), ('LemonMilk', 'LemonMilk'), ('MoonTank', 'MoonTank'), ('Vogue', 'Vogue')], default='Roboto', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='font_size',
            field=models.CharField(choices=[('14px', 'Small'), ('16px', 'Normal'), ('20px', 'Large'), ('24px', 'Extra Large')], default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_position',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='logo_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='menu_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lobster', 'Lobster'), ('Pacifico', 'Pacifico'), ('Vendya', 'Vendya'), ('Caviar Dreams', 'Caviar Dreams'), ('Gavoline', 'Gavoline'), ('Heavitas', 'Heavitas'), ('LemonMilk', 'LemonMilk'), ('MoonTank', 'MoonTank'), ('Vogue', 'Vogue')], default='Roboto', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='font_size',
            field=models.CharField(choices=[('14px', 'Small'), ('16px', 'Normal'), ('20px', 'Large'), ('24px', 'Extra Large')], default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_position',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='layout',
            field=models.CharField(choices=[('column', 'Column'), ('row', 'Row')], default='column', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='menu_item_image'),
        ),
    ]
