# Generated by Django 5.2.1 on 2025-07-31 19:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuconfig',
            name='title_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='title_font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lobster', 'Lobster'), ('Pacifico', 'Pacifico'), ('Vendya', 'Vendya'), ('Caviar Dreams', 'Caviar Dreams'), ('Gavoline', 'Gavoline'), ('Heavitas', 'Heavitas'), ('LemonMilk', 'LemonMilk'), ('MoonTank', 'MoonTank'), ('Vogue', 'Vogue')], default='Roboto', max_length=100),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='title_font_size',
            field=models.CharField(choices=[('14px', 'Small'), ('16px', 'Normal'), ('20px', 'Large'), ('24px', 'Extra Large')], default='20px', max_length=10),
        ),
        migrations.AddField(
            model_name='menuconfig',
            name='title_text',
            field=models.CharField(default='Menu', max_length=100),
        ),
    ]
