# Generated by Django 5.2.1 on 2025-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuconfig_title_color_menuconfig_title_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='font_size',
            field=models.CharField(choices=[('25px', 'Small'), ('45px', 'Normal'), ('65px', 'Large'), ('85px', 'Extra Large'), ('105px', 'XXL')], default='45px', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuconfig',
            name='title_font_size',
            field=models.CharField(choices=[('25px', 'Small'), ('45px', 'Normal'), ('65px', 'Large'), ('85px', 'Extra Large'), ('105px', 'XXL')], default='45px', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='font_size',
            field=models.CharField(choices=[('25px', 'Small'), ('45px', 'Normal'), ('65px', 'Large'), ('85px', 'Extra Large'), ('105px', 'XXL')], default='45px', max_length=10),
        ),
    ]
